# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  bl_caster_l_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  bl_caster_r_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  bl_caster_rotation_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  br_caster_l_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  br_caster_r_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  br_caster_rotation_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  fl_caster_l_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  fl_caster_r_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  fl_caster_rotation_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  fr_caster_l_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  fr_caster_r_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15
    has_acceleration_limits: false
    max_acceleration: 0
  fr_caster_rotation_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  head_pan_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  head_tilt_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  l_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: false
    max_acceleration: 0
  l_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_l_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_motor_screw_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_motor_slider_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_r_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_r_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: false
    max_acceleration: 0
  l_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  laser_tilt_mount_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  r_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: false
    max_acceleration: 0
  r_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  r_gripper_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  r_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_gripper_l_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_gripper_motor_screw_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  r_gripper_motor_slider_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  r_gripper_r_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_gripper_r_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: false
    max_acceleration: 0
  r_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  torso_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.013
    has_acceleration_limits: false
    max_acceleration: 0
  torso_lift_motor_screw_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0